### ISSUE TITLE
Cannot create raw cache and cube cache.

### ISSUE THREAD

**Issue by zzcclp** [alibaba/SparkCube#6]
when to create raw cache，it show below error message：
`Cannot persistent default.cube_test into hive metastore as table property keys may not start with 'spark.sql.': [spark.sql.cached.info.raw.enableRewrite, spark.sql.cached.info.raw.cacheColumns, spark.sql.cached.info.raw, spark.sql.cached.info.raw.zorderBy, spark.sql.cached.info.raw.storagePath, spark.sql.cached.info.raw.provider, spark.sql.cached.info.raw.lastUpdatedTime, spark.sql.cached.info.raw.partitionBy, spark.sql.cached];
`

when to create cube cache，it show below error message：
`Cannot persistent default.cube_test into hive metastore as table property keys may not start with 'spark.sql.': [spark.sql.cached.info.cube, spark.sql.cached.info.cube.lastUpdatedTime, spark.sql.cached.info.cube.storagePath, spark.sql.cached.info.cube.provider, spark.sql.cached.info.cube.enableRewrite, spark.sql.cached, spark.sql.cached.info.cube.measures, spark.sql.cached.info.cube.partitionBy, spark.sql.cached.info.cube.dims];`

**Comment by frankleaf** [comment]
already fixed
